### PR TITLE
Fix csrf middleware behavior with header key lookup

### LINKED ISSUE #2045: 🐛 [Bug]: Strange CSRF middleware behavior with header KeyLookup configuration
### Bug Description

> Discord [discussion](https://discord.com/channels/704680098577514527/704682020990746624/1011604136111898664)

The middleware randomly starts responding with **403 Forbidden** if it's configured to look up for `header:X-Csrf-Token`. I found that the storage's map keys are messing up with random header values, so possibly this has something to do with unsafe magic.

One moment you have a map entry with a valid key which is actually a recently added CSRF token, a couple of requests ago you check this map and you see a random header value that replaced the first characters of the key, it can't be found by the middleware which results in returning the Forbidden response.

image

### How to Reproduce

1. Use a default CSRF middleware for all your endpoints
2. Obtain your token with the GET request
3. Keep making POST requests and eventually you'll get **403 Forbidden**

### Expected Behavior

Technically, storage's map keys shouldn't mess up with random header values. CSRF middleware working correctly.

### Fiber Version

v2.34.1

### Code Snippet (optional)

_No response_

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

### PR DESCRIPTION
**Pull request by ReneWerner87**
## Description
This should
Fixes #2045

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I tried to make my code as fast as possible with as few allocations as possible
- [x] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

File: middleware/csrf/csrf_test.go [hunk 1]
```diff
@@ -340,3 +340,111 @@ func Test_CSRF_ErrorHandler_EmptyToken(t *testing.T) {
 	utils.AssertEqual(t, 419, ctx.Response.StatusCode())
 	utils.AssertEqual(t, "empty CSRF token", string(ctx.Response.Body()))
 }
+
+// TODO: use this test case and make the unsafe header value bug from https://github.com/gofiber/fiber/issues/2045 reproducible and permanently fixed/tested by this testcase
```
Comment (ReneWerner87) [inline middleware/csrf/csrf_test.go:344]: https://github.com/gofiber/fiber/issues/2045#issuecomment-1231452274

**Review by efectn — APPROVED** [review]
