### PR TITLE
Changing default log output

### LINKED ISSUE #2729: 🐛 [Bug]: Logger middleware default Format isn't the format that's used
### Bug Description

> I'm filing this as a bug since I think the behaviour is counter-intuitive.

The logger middleware has a configuration with a default format: https://github.com/gofiber/fiber/blob/2374cad3cd109d3bf33f5863e6eb14c32de1882e/middleware/logger/config.go#L89

However, when the logger proceeds to print this, it ignores the actual format: https://github.com/gofiber/fiber/blob/2374cad3cd109d3bf33f5863e6eb14c32de1882e/middleware/logger/logger.go#L141-L174

Despite it checking for if it should use the default format, it then uses a different format string in the `fmt.Sprintf()` calls.

### How to Reproduce

* Add the logging middleware without overriding the `Format`
* Do a request and observe the log output

### Expected Behavior

Logged line should use the `ConfigDefault.Format` for output, as shown in the configuration: https://docs.gofiber.io/api/middleware/logger#default-config

### Fiber Version

v2.50.0

### Code Snippet (optional)

_No response_

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

### PR DESCRIPTION
**Pull request by brunodmartins**
## Description

The default log Format described on [here](https://github.com/brunodmartins/fiber/blob/1b060cb150c6eab80f71e51120b05da555b43c27/middleware/logger/config.go#L89) is not respected on the Log middleware, as described on the related issue.

Looking at the beginning of the middleware, before it starts it completes the configuration filling the missing options with the default ones, thus, if a user do not override the Format parameter, the default one shall be used instead. This configuration is later on loaded on the `templateChain` and `logFunChain`.

```golang
templateChain, logFunChain, err := buildLogFuncChain(&cfg, createTagMap(&cfg))
```

Thus, even if a user do not provide a Format, the middleware shall build a log func chain and could use it later. 

To **avoid breaking** client logs, I modified the expected default log format, to be equal as the one that has been used on the middleware. 

image

Fixes #2729

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## Checklist:

- [ ] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation - /docs/ directory for https://docs.gofiber.io/
- [x] New and existing unit tests pass locally with my changes

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

File: middleware/logger/logger.go [hunk 1]
```diff
@@ -85,9 +85,6 @@ func New(config ...Config) fiber.Handler {
 			return c.Next()
 		}
 
-		// Alias colors
-		colors := c.App().Config().ColorScheme
```
Comment (gaby) [inline middleware/logger/logger.go:89]: Why was this removed?

**Review by gaby — CHANGES_REQUESTED** [review]
We need a unit-test to validate the logs are in the expected output format

File: middleware/logger/logger.go (hunk 1 above)
Comment (brunodmartins) [reply middleware/logger/logger.go:89]: Because this variable was not used anymore

**Comment by brunodmartins** [comment]
Ouch! It's was passing here! I will check it again

**Comment by brunodmartins** [comment]
@gaby the test that failed is not related to my change: 

--- FAIL: Test_CSRF_ExpiredToken (1.00s)

Could this be another problem?

**Comment by ReneWerner87** [comment]
> @gaby the test that failed is not related to my change:
> 
> --- FAIL: Test_CSRF_ExpiredToken (1.00s)
> 
> Could this be another problem?

yes, there are some tests with race conditions -> we are on it

**Review by skydiver1980 — APPROVED** [review]

File: middleware/logger/logger.go [hunk 2]
```diff
@@ -137,56 +134,6 @@ func New(config ...Config) fiber.Handler {
 		// Get new buffer
 		buf := bytebufferpool.Get()
 
-		// Default output when no custom Format or io.Writer is given
-		if cfg.Format == ConfigDefault.Format {
```
Comment (ReneWerner87) [inline middleware/logger/logger.go:141]: not sure, is this part no longer needed ? where is this code now covered ?

**Comment by gaby** [comment]
@brunodmartins Can you fix the merge conflicts?

**Comment by brunodmartins** [comment]
@gaby I solved the merge commit with my changes, as I commented on the PR description: to do not break current client logs format, I kept the one that as been used due to the bug

File: middleware/logger/logger.go (hunk 1 above)
Comment (ReneWerner87) [reply middleware/logger/logger.go:89]: i checked it again -> its fine

**Comment by ReneWerner87** [comment]
i tested the change
image

without colors:
image

default with colors:
image

with special format:
image

LGTM

**Review by gaby — APPROVED** [review]

File: middleware/logger/logger.go (hunk 2 above)
Comment (ReneWerner87) [reply middleware/logger/logger.go:141]: thanks, this old colorization is therefore superfluous, since the enabledColors are queried in the methods for the tags

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
@brunodmartins thank you for cleaning up, now we have one less big block to maintain
and sorry for the long wait

**Comment by brunodmartins** [comment]
Thanks for the help on this contribution =)

**Review by efectn — APPROVED** [review]
