### PR TITLE
🐛 bug: Handle Unix sockets in adaptor middleware

### LINKED ISSUE #3751: 🐛 [Bug]: Unix domain socket with Adaptor gives Internal Server Error
### Bug Description

Unix domain socket gives an Internal Server Error using adaptor middleware

### How to Reproduce

1. Run the following code snippet (attached)
2. Curl the endpoint  ` curl --unix-socket /tmp/test.sock http://localhost/hello`
3. Response: Internal Server Error

### Expected Behavior

`{"message":"Hello from Fiber with http.Server!"}% `

### Fiber Version

v2.52.9

### Code Snippet (optional)

```go
package main

import (
	"log"
	"net"
	"net/http"
	"os"
	"syscall"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/adaptor"
)

var socketPath = "/tmp/test.sock"

func main() {
	app := fiber.New(fiber.Config{})

	app.Get("/hello", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{
			"message": "Hello from Fiber with http.Server!",
		})
	})

	if _, err := os.Stat(socketPath); !os.IsNotExist(err) {
		if err = syscall.Unlink(socketPath); err != nil {
			log.Fatalf("socket remove error: %s\n", err.Error())
		}
	}
	
	listener, err := net.Listen("unix", socketPath)
	if err != nil {
		log.Fatal(err.Error())
	}

	// Create an http.Handler from Fiber
	handler := adaptor.FiberApp(app)

	if err := http.Serve(listener, handler); err != nil {
		log.Fatalf("error serving on unix socket: %v", err)
	}
 
      // log.Fatal(app.Listener(listener)) - this works
}
```

### Checklist:

- [x] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/main/.github/CODE_OF_CONDUCT.md).
- [x] I have checked for existing issues that describe my problem prior to opening this one.
- [x] I understand that improperly formatted bug reports may be closed without explanation.

### PR DESCRIPTION
**Pull request by Dishank-Sen**
# PR Title

🐛 Fix adaptor.FiberApp to handle Unix sockets + ✅ add unit test

# Description

This PR fixes a bug in `adaptor.FiberApp` that caused requests over Unix domain sockets to return a `500 Internal Server Error`.

The issue was due to improper handling of `RemoteAddr` for Unix socket connections. A fallback mechanism has been added to correctly handle requests via Unix sockets.

Additionally, a new unit test has been added to validate Unix socket support.

## Changes introduced

- Fixed `adaptor.FiberApp` to properly handle `RemoteAddr` for Unix socket requests.  
- Added `unixsocket_test.go` to validate Unix domain socket functionality.  

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)  
- [x] Enhancement (improvement to existing functionality)  
- [x] Test addition (new unit test for Unix socket support)  

## Checklist

- [x] Self-reviewed the code and added comments where necessary.  
- [x] Added unit test for Unix socket support.  
- [x] Verified all unit tests pass locally.  
- [x] Ensured no unnecessary dependencies were introduced.  

Fixes #3751

### CODE REVIEW

**Comment by gaby** [comment]
@Dishank-Sen The last comment from CodeRabbit has a section called "Nitpick commente", see if those help with the test failures

**Comment by gaby** [comment]
@Dishank-Sen Tests are passing, just a small lint issue with re-declaration of `err`

**Comment by Dishank-Sen** [comment]
@gaby  Could you please review this and let me know if it looks good for approval?

**Comment by Dishank-Sen** [comment]
@gaby All tests are passing on this PR. Just wanted to kindly ask if there’s anything else needed from my side to move this forward, or if it’s ready for review/merge. Thanks for your time .

**Comment by gaby** [comment]
@Dishank-Sen Will merge this today

File: middleware/adaptor/adaptor.go [hunk 1]
```diff
@@ -168,10 +168,14 @@ func handlerFunc(app *fiber.App, h ...fiber.Handler) http.HandlerFunc {
 			r.RemoteAddr = net.JoinHostPort(r.RemoteAddr, "80")
 		}
 
-		remoteAddr, err := net.ResolveTCPAddr("tcp", r.RemoteAddr)
```
Comment (ReneWerner87) [inline middleware/adaptor/adaptor.go:171]: i would prefer to keep the error handling
```go
	remoteAddr, err := resolveRemoteAddr(r.RemoteAddr, r.Context().Value(http.LocalAddrContextKey))
```

and just use the `ResolveTCPAddr("unix" ....)` function
```go
func isUnixNetwork(network string) bool {
	switch network {
		case "unix", "unixgram", "unixpacket":
			return true
		default:
			return false
	}
}


func resolveRemoteAddr(remoteAddr string, localAddr any) (net.Addr, error) {
	if addr, ok := localAddr.(net.Addr); ok && isUnixNetwork(addr.Network()) {
		return net.ResolveUnixAddr("unix", addr)
	}

	resolved, err := net.ResolveTCPAddr("tcp", remoteAddr)
	if err == nil {
		return resolved, nil
	}
 
	var addrErr *net.AddrError
	if errors.As(err, &addrErr) && addrErr.Err == "missing port in address" {
		remoteAddr = net.JoinHostPort(remoteAddr, "80")
		return net.ResolveTCPAddr("tcp", remoteAddr)
	}
	 
	return nil, err
}
```

@Dishank-Sen @gaby WDYT?

Comment (Dishank-Sen) [reply middleware/adaptor/adaptor.go:171]: @ReneWerner87 Yeah this is a cleaner approach and I have added resolveRemoteAddr function.

**Review by gaby — APPROVED** [review]

**Review by sixcolors — CHANGES_REQUESTED** [review]
Hi @Dishank-Sen! I noticed there were some test coverage gaps and also there is a potential panic issue in the `CopyContextToFiberContext` function (outside of diff range). I've been working on some improvements locally - would you be interested in collaborating? I can either:

1. Share the fixes with you so you can add them to your branch
2. Create a separate follow-up PR after yours is merged
3. Help you implement the fixes if you prefer

What would work best for you?

**Comment by Dishank-Sen** [comment]
@sixcolors I’d be happy to collaborate. Feel free to share the fixes and I’ll add them, or open a follow-up PR — whichever you prefer.

**Comment by sixcolors** [comment]
[unix-socket-improvements.patch](https://github.com/user-attachments/files/22584131/unix-socket-improvements.patch)

**Comment by sixcolors** [comment]
[unix-socket-improvements.patch](https://github.com/user-attachments/files/22584167/unix-socket-improvements.patch)

Was before [4d25336](https://github.com/gofiber/fiber/pull/3760/commits/4d253364c2d8278aee19755b263783d602a7012c), but contained coverage that it included as well as coverage for other missing lines outside of the diff range.

**Comment by gaby** [comment]
@Dishank-Sen Did you apply the changes from @sixcolors patch?

**Comment by Dishank-Sen** [comment]
@gaby As of my last commit, I haven’t applied the changes from @sixcolors’ patch yet.
