### PR TITLE
♻️ refactor: Make genericParseType return error

### LINKED ISSUE #3393: 📝 [Proposal]: genericParseType should return error for error handling
### Feature Proposal Description

When `genericParseType` encounters a parsing error and no default value is set, it silently sets the zero value without returning an error or panicking.

```go
func TestGeneric(t *testing.T) {
    var v int8
    u := genericParseType("2000", v)
    fmt.Println(u)
}
```
```
> go test --run TestGeneric -v
=== RUN   TestGeneric
0
--- PASS: TestGeneric (0.00s)
```

In my opinion, the return value of `genericParseType` should include an `error`. Functions like `Query`, `Params`, and `GetReqHeader` use `genericParseType`, but there is no error handling when parsing unexpected values.

### Alignment with Express API

None

### HTTP RFC Standards Compliance

None

### API Stability

None

### Feature Examples

```go
func genericParseType[V GenericType](str string, v V, defaultValue ...V) (V, error)
func GetReqHeader[V GenericType](c Ctx, key string, defaultValue ...V) (V, error)
func Params[V GenericType](c Ctx, key string, defaultValue ...V) (V, error)
func Query[V GenericType](c Ctx, key string, defaultValue ...V) (V, error)

// If `defaultValue` is not set and a parsing error occurs, an error should be returned.
```

### Checklist:

- [x] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [x] I have searched for existing issues that describe my proposal before opening this one.
- [x] I understand that a proposal that does not meet these guidelines may be closed without explanation.

### PR DESCRIPTION
**Pull request by ksw2000**
# Description

The original `genericParseType` function returned a default value when errors occurred, which made it unclear whether a parsing error had actually happened. I've refactored `genericParseType` to explicitly return an error, improving error handling clarity. 

Furthermore, `ctx_test.go` contained excessive redundant code related to testing `genericParseType`. I've streamlined these tests to improve the overall clarity and cleanliness of the codebase.

Resolves #3393 

## Type of change

- [x] Enhancement (improvement to existing features and functionality)
- [x] Code consistency (non-breaking change which improves code reliability and robustness)

## Checklist

Before you submit your pull request, please make sure you meet these requirements:

- [ ] Followed the inspiration of the Express.js framework for new functionalities, making them similar in usage.
- [x] Conducted a self-review of the code and provided comments for complex or critical parts.
- [ ] Updated the documentation in the `/docs/` directory for [Fiber's documentation](https://docs.gofiber.io/).
- [x] Added or updated unit tests to validate the effectiveness of the changes or new features.
- [x] Ensured that new and existing unit tests pass locally with the changes.
- [x] Verified that any new dependencies are essential and have been agreed upon by the maintainers/community.
- [x] Aimed for optimal performance with minimal allocations in the new code.
- [ ] Provided benchmarks for the new code to analyze and improve upon.

### CODE REVIEW

File: ctx.go [hunk 1]
```diff
@@ -1115,8 +1122,11 @@ func (c *DefaultCtx) Params(key string, defaultValue ...string) string {
 // http://example.com/id/:number -> http://example.com/id/john
 // Params[int](c, "number", 0) -> returns 0 because can't parse 'john' as integer.
 func Params[V GenericType](c Ctx, key string, defaultValue ...V) V {
-	var v V
-	return genericParseType(c.Params(key), v, defaultValue...)
+	v, err := genericParseType[V](c.Params(key))
+	if err != nil && len(defaultValue) > 0 {
+		return defaultValue[0]
```
Comment (gaby) [inline ctx.go:1127]: My only concern is line 1127 not being covered by the tests

**Review by gaby — CHANGES_REQUESTED** [review]
LGTM, we just expand the tests a bit to cover all the missing lines from coverage report.

**Comment by ReneWerner87** [comment]
@ksw2000 can you check the missing coverage and add test for this
https://github.com/gofiber/fiber/pull/3473/checks?check_run_id=42849607278

**Review by ReneWerner87 — APPROVED** [review]
