### PR TITLE
:bug: bug: fix middleware naming and returned values of group methods

### LINKED ISSUE #2467: 🐛 [Bug]: Naming for Middlewares
### Bug Description

Currently naming on middlewares just working for last element of RequestMethods slice (it's PATCH as default). That's not expected behavior and it needs to be fixed.

```
Path: /, Method: GET, Name: 
Path: /, Method: HEAD, Name: 
Path: /, Method: POST, Name: 
Path: /, Method: PUT, Name: 
Path: /, Method: DELETE, Name: 
Path: /, Method: CONNECT, Name: 
Path: /, Method: OPTIONS, Name: 
Path: /, Method: TRACE, Name: 
Path: /, Method: PATCH, Name: test
```

### How to Reproduce

1. Add middleware and name it.
2. Naming will only apply to PATCH method.

### Expected Behavior

All methods of middleware should have the name.

```
Path: /, Method: GET Name: test
Path: /, Method: HEAD, Name: test
Path: /, Method: POST, Name: test
Path: /, Method: PUT, Name: test
Path: /, Method: DELETE, Name: test
Path: /, Method: CONNECT, Name: test
Path: /, Method: OPTIONS, Name: test
Path: /, Method: TRACE, Name: test
Path: /, Method: PATCH, Name: test
```

### Fiber Version

After naming feature introduced

### Code Snippet (optional)

```go
package main

import (
	"fmt"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	app.Use(func(c *fiber.Ctx) error {
		return c.Next()
	}).Name("test")

	for _, route := range app.GetRoutes() {
		fmt.Printf("Path: %s, Method: %s, Name: %s\n", route.Path, route.Method, route.Name)
	}
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

### PR DESCRIPTION
**Pull request by ytsruh**
## Description
Edited app.Name() method to add a name parameter to reach route unless already assigned. This required looping over app.stack which feels ineffecient but it was the only method of accessing all of the routes that I could find

Fixes # (issue)
Resolves #2467 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation - /docs/ directory for https://docs.gofiber.io/
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [x] I tried to make my code as fast as possible with as few allocations as possible
- [ ] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

File: app.go [hunk 1]
```diff
@@ -609,12 +609,17 @@ func (app *App) SetTLSHandler(tlsHandler *TLSHandler) {
...
 	app.mutex.Lock()
-
-	latestGroup := app.latestRoute.group
-	if latestGroup != nil {
-		app.latestRoute.Name = latestGroup.name + name
-	} else {
-		app.latestRoute.Name = name
+	for _, routes := range app.stack {
+		for _, route := range routes {
+			latestGroup := app.latestRoute.group
```
[the remark this answers is not in the document]
Comment (ytsruh) [reply app.go:614]: Thanks for quick review. Will get this fixed (& the lint check) and update later this afternoon.

File: app_test.go [hunk 2]
```diff
@@ -1803,3 +1803,31 @@ func TestApp_GetRoutes(t *testing.T) {
 		utils.AssertEqual(t, name, route.Name)
 	}
 }
+
+func TestRouteName(t *testing.T) {
+	home, named := "home", "named"
+	app := New()
+
+	app.Use(func(c *Ctx) error {
```
Comment (ReneWerner87) [inline app_test.go:1811]: what happens if we define 2 middlewares with names one after the other?

can you add this to your test case 

and maybe one middleware which has no name

Comment (ytsruh) [reply app_test.go:1811]: Thanks for quick review. Yes I have 3 test cases, two with names & one unnamed - they all pass. Without looping over the stack the names were overwriting each other so this was the only way I found to resolve this problem

**Comment by ytsruh** [comment]
Right updated to pass lint rules & moved the variable outside of the loop

File: app_test.go (hunk 2 above)
Comment (ReneWerner87) [reply app_test.go:1811]: the case for the middelwares with prefix matching is a little bit different

can you add additional route declarations
```go
app.Use(func(c *Ctx) error {
    return c.Next()
}).Name("corsMW")

app.Use(func(c *Ctx) error {
    return c.Next()
}).Name("compressMW")

app.Use(func(c *Ctx) error {
    return c.Next()
})// no name
```

and check the expectation

Comment (ReneWerner87) [reply app_test.go:1811]: can you include these cases in our tests

would like to prevent that the different declarations of the different routes with the same path influence each other.

Comment (ytsruh) [reply app_test.go:1811]: Sure will add in for review.

But to be honest, I think you'll need to reject this PR. Looping over the stack is going to cause the paths to overwrite each other so I do think this will need a different solution.

Comment (ytsruh) [reply app_test.go]: Right I've added in as requested, but I'm less confident this meets expectations now so understand if you prefer to reject.

File: app.go [hunk 3]
```diff
@@ -609,12 +609,17 @@ func (app *App) SetTLSHandler(tlsHandler *TLSHandler) {
...
 	app.mutex.Lock()
+	for _, routes := range app.stack {
+		for _, route := range routes {
+			if route.Path == app.latestRoute.path {
+				route.Name = name
+			}
+		}
+	}
 
 	latestGroup := app.latestRoute.group
```
Comment (efectn) [inline app.go:620]: Can you add test cases for group and use

Comment (ytsruh) [reply app.go:620]: I added a test for Group locally and it failed. Sadly, I'm not able to get the group names to work as group was always <nil>

Sorry about this

**Comment by ReneWerner87** [comment]
Will check it tomorrow

**Review by ReneWerner87 — APPROVED** [review]
