### PR TITLE
fix: Decompress request body when multi Content-Encoding sent on request headers

### LINKED ISSUE #2085: 🤗 [Question]: How to get the RAW body?
### Question Description

I want to support multi- `Content-Encoding`.

I find the method `Body()` that is supposed to give me the **raw** body. But when I check the source code, it seems to decompress some encodings by default.

For example, when it is `gzip`, I can call `Body()` to get the decompressed body, while it is `snappy`, I will have to handle the decompression logic myself.

Could you teach me if there's a better way to handle decompression?

https://github.com/gofiber/fiber/blob/8ec62a64cc8367372cd9eb1fc48eba380ee01bdf/ctx.go#L281-L311

### Code Snippet (optional)

_No response_

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

### PR DESCRIPTION
**Pull request by Jictyvoo**
## Description

Currently the Ctx.Body() implementation doesn't parse multi content-encoding body, so in order to attend [RFC9110](https://www.rfc-editor.org/rfc/rfc9110#section-8.4-5), the Body method was changed, and a new wrapper method to body raw was made.

Fixes #2085 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation - /docs/ directory for https://docs.gofiber.io/
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [x] I tried to make my code as fast as possible with as few allocations as possible
- [x] For new code I have written benchmarks so that they can be analyzed and improved

### CODE REVIEW

**Comment by gaby** [comment]
@Jictyvoo Thank you for the PR, can you take a look at all the issues raised by golangci-lint. GoFiber currently supports go 1.17-1.20 and some of the functions added in the unit-test are only available in 1.20

**Comment by Jictyvoo** [comment]
@gaby Oh, I see, I forget about this lint rules. Already applied all changes needed to pass in the linter. Also, for the `errors.Join` function, I replaced it to run on previous Go versions also.

File: ctx.go [hunk 1]
```diff
@@ -260,33 +260,60 @@ func (c *Ctx) BaseURL() string {
...
-		body, err = c.fasthttp.Request.BodyUnbrotli()
-	case StrDeflate:
-		body, err = c.fasthttp.Request.BodyInflate()
-	default:
-		body = c.fasthttp.Request.Body()
+		if err != nil {
+			return []byte(err.Error())
+		}
+
+		if index < len(encodingOrder)-1 {
```
Comment (efectn) [inline ctx.go:305]: Can you add a testcase for this usecase

Comment (Jictyvoo) [reply ctx.go]: Done it, I also add some more testcases, for the error and others

**Review by efectn — APPROVED** [review]

**Review by gaby — APPROVED** [review]
LGTM, although this probably requires updating the version given there's quite a lot changing in Body()

**Comment by efectn** [comment]
@Jictyvoo can you also update docs, i forgot mentioning it

**Comment by ReneWerner87** [comment]
@Jictyvoo can you share the times of the benchmark for before and after

**Comment by Jictyvoo** [comment]
> @Jictyvoo can you share the times of the benchmark for before and after

Previous Change:
```txt
goos: linux
goarch: amd64
pkg: github.com/gofiber/fiber/v2
cpu: AMD Ryzen 7 5800X 8-Core Processor             
Benchmark_Ctx_Body_With_Compression
Benchmark_Ctx_Body_With_Compression/gzip
Benchmark_Ctx_Body_With_Compression/gzip-16         	 1882047	       658.6 ns/op	     145 B/op	       7 allocs/op
Benchmark_Ctx_Body_With_Compression/deflate
Benchmark_Ctx_Body_With_Compression/deflate-16      	 2226450	       497.1 ns/op	     129 B/op	       4 allocs/op
Benchmark_Ctx_Body
Benchmark_Ctx_Body-16    	100000000	        13.36 ns/op	       0 B/op	       0 allocs/op
PASS
```

Current Change:
```txt
goos: linux
goarch: amd64
pkg: github.com/gofiber/fiber/v2
cpu: AMD Ryzen 7 5800X 8-Core Processor             
Benchmark_Ctx_Body_With_Compression
Benchmark_Ctx_Body_With_Compression/gzip
Benchmark_Ctx_Body_With_Compression/gzip-16         	 1445175	       728.0 ns/op	     145 B/op	       7 allocs/op
Benchmark_Ctx_Body_With_Compression/gzip,invalid
Benchmark_Ctx_Body_With_Compression/gzip,invalid-16 	 1521243	       806.5 ns/op	     194 B/op	       8 allocs/op
Benchmark_Ctx_Body_With_Compression/deflate
Benchmark_Ctx_Body_With_Compression/deflate-16      	 1965168	       591.5 ns/op	     129 B/op	       4 allocs/op
Benchmark_Ctx_Body_With_Compression/gzip,deflate
Benchmark_Ctx_Body_With_Compression/gzip,deflate-16 	  663676	      1508 ns/op	     377 B/op	      12 allocs/op
Benchmark_Ctx_Body
Benchmark_Ctx_Body-16    	89043600	        13.13 ns/op	       0 B/op	       0 allocs/op
PASS
```


1. Benchmark_Ctx_Body_With_Compression/gzip-16:
    - Performance has decreased, from executing 1,882,047 operations at 658.6 ns/op to 1,445,175 at 728.0 ns/op.
    - The memory usage and allocations per operation stay the same - 145 B/op at 7 allocs/op.
2. Benchmark_Ctx_Body_With_Compression/deflate-16:
    - Performance has also decreased, from executing 2,226,450 operations at 497.1 ns/op to 1,965,168 at 591.5 ns/op.
    - Memory usage and allocations per operation stay the same - 129 B/op at 4 allocs/op.
3. Benchmark_Ctx_Body-16:
    - Performance is almost the same from executing 100,000,000 operations at 13.36 ns/op to 89,043,600 at 13.13 ns/op.
    - The memory usage and allocations per operation remain the same - 0 B/op at 0 allocs/op.

**Comment by ReneWerner87** [comment]
thx, looks almost the same -> no performance lose

**Comment by Jictyvoo** [comment]
> @Jictyvoo can you also update docs, i forgot mentioning it

Have updated some, I don't know if it has others than `docs/api/ctx.md`

**Comment by Jictyvoo** [comment]
This failed test, I don't see as something that I change, any of you know something about it?

**Review by ReneWerner87 — APPROVED** [review]
