### PR TITLE
🐛 bug: fix proxy overwrote the wrong scheme

### LINKED ISSUE #2001: 🐛 [Bug]: Middleware proxy.Do overwrote the wrong scheme
### Bug Description

I am making a simple proxy that you can append the proxied url after /, for example, you can request http://localhost:3333/http://ip-api.com/json/1.1.1.1 , which will proxy request to http://ip-api.com/json/1.1.1.1.

Here is my code:

```golang
package main

import (
	"strings"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/proxy"
)

func main() {
	app := fiber.New()
	app.Get("/*", func(c *fiber.Ctx) error {
		path := c.OriginalURL()
		url := strings.TrimPrefix(path, "/")
		if err := proxy.Do(c, url); err != nil {
			return err
		}
		c.Response().Header.Del(fiber.HeaderServer)
		return nil
	})
	app.Listen(":3333")
}
```

When I request the url like: http://localhost:3333/http://ip-api.com/json/1.1.1.1 , it will show this error:
> unsupported protocol "ttp". http and https are supported

By debugging and following the code, the scheme has been overwritten to "ttp" at this line: https://github.com/gofiber/fiber/blob/master/middleware/proxy/proxy.go#L131 , since at some point the `addr` variable has changed to "ttp://xxxxx" (without the leading "h"), the parsed scheme changed to "ttp". It seems related to the memory allocation, the problem will be gone, if in my code I either:

* change the fiber config to use `Immutable: true`, or 
* change `path := c.OriginalURL()` to `path := utils.CopyString(c.OriginalURL())` .

But since the code above doesn't violate fiber's rule:
> As a rule of thumb, you must only use context values within the handler, and you must not keep any references.

Even if I don't use `Immutable: true` or `utils.CopyString`, the problem shouldn't be there. 

Also, this bug doesn't exist when I was using version v2.10.0, which doesn't have these 3 lines: https://github.com/gofiber/fiber/blob/master/middleware/proxy/proxy.go#L130

### How to Reproduce

Copy the above code and run it with fiber v2.36.0, then visit: http://localhost:3333/http://ip-api.com/json/1.1.1.1 .
You should be able to see the error: 
> unsupported protocol "ttp". http and https are supported

I can reproduce this in my 3 laptops: Macbook m1, Mackbook m2 and Macbook Intel.

### Expected Behavior

The error shouldn't be there (the scheme shouldn't be incorrectly overwritten) even without "Immutable: true" config or CopyString

### Fiber Version

v2.36.0

### Code Snippet (optional)

See above

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

### PR DESCRIPTION
**Pull request by wangjq4214**
**Please provide enough information so that others can review your pull request:**

Fix proxy overwrote the wrong scheme

**Explain the *details* for making this change. What existing problem does the pull request solve?**

close #2001

**Commit formatting** 

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

File: middleware/proxy/proxy.go [hunk 1]
```diff
@@ -123,11 +123,13 @@ func Do(c *fiber.Ctx, addr string) error {
 	res := c.Response()
 	originalURL := utils.CopyString(c.OriginalURL())
 	defer req.SetRequestURI(originalURL)
-	req.SetRequestURI(addr)
+
+	copiedURL := utils.CopyString(addr)
+	req.SetRequestURI(copiedURL)
```
Comment (ReneWerner87) [inline middleware/proxy/proxy.go:128]:
```suggestion
	req.SetRequestURI(utils.CopyString(addr))
```
this should be enough, because within the string is changed

File: middleware/proxy/proxy.go [hunk 2]
```diff
@@ -123,11 +123,13 @@ func Do(c *fiber.Ctx, addr string) error {
...
 	// NOTE: if req.isTLS is true, SetRequestURI keeps the scheme as https.
 	// issue reference:
 	// https://github.com/gofiber/fiber/issues/1762
-	if scheme := getScheme(utils.UnsafeBytes(addr)); len(scheme) > 0 {
+	if scheme := getScheme(utils.UnsafeBytes(copiedURL)); len(scheme) > 0 {
```
Comment (ReneWerner87) [inline middleware/proxy/proxy.go:132]:
```suggestion
	if scheme := getScheme(utils.UnsafeBytes(addr)); len(scheme) > 0 {
```
and this back to before

**Review by ReneWerner87 — CHANGES_REQUESTED** [review]

**Comment by ReneWerner87** [comment]
thanks for the work, can you look over my comments

File: middleware/proxy/proxy.go (hunk 2 above)
Comment (wangjq4214) [reply middleware/proxy/proxy.go:132]: This modification still has the original problem, and I haven't explored the cause. The `addr` will change after running `req.SetRequestURI` regardless of the data passed in.

I'll probably explore the reasons over the weekend.

**Comment by wangjq4214** [comment]
> thanks for the work, can you look over my comments

In this scenario, addr is a slice reference to the `[]byte c.fasthttp.Request.Header.requestURI`, so when **SetRequestURI** is executed the requestURI changes causing addr to change as well. 

More specifically, for the above example, addr is equivalent to requestURI[1:], so after the requestURI changes from /http://ip-api.com/json to http://ip-api.com/json addr will change from http://ip-api.com/json to ttp://ip-api.com/json, causing SetSchema to fail.

**Comment by ReneWerner87** [comment]
since this removes the link to the variable with the addr, the following change is then no longer necessary

**Comment by wangjq4214** [comment]
> since this removes the link to the variable with the addr, the following change is then no longer necessary

image

image

When I use the modifications you mentioned above, I can't pass the test.

In SetRequestURI, `h.requestURI = append(h.requestURI[:0], requestURI...)` will be executed. Because the resulting []byte is shorter than the original one, he will execute in the original []byte. And no memory will be allocated.

File: middleware/proxy/proxy.go (hunk 2 above)
Comment (ReneWerner87) [reply middleware/proxy/proxy.go:132]: i was wrong -> your code is okay

File: middleware/proxy/proxy.go (hunk 1 above)
Comment (ReneWerner87) [reply middleware/proxy/proxy.go:128]: i was wrong -> your code is okay

**Review by ReneWerner87 — APPROVED** [review]
