### PR TITLE
🐛 Make SendFile return 404 if file not found

### LINKED ISSUE #905: 🐛 https://github.com/gofiber/fiber/issues/903#issue-718030679
**Fiber version**

**Issue description**

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()

  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}
```

### LINKED ISSUE #907: 🐛  Sendfile's status is overwrote by ErrorHandler
**Fiber version**
v2.0.6

**Issue description**
expect 404, got 500

https://github.com/gofiber/fiber/blob/v2.0.6/ctx.go#L956
https://github.com/gofiber/fiber/blob/v2.0.6/app.go#L272

**Code snippet**

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
)

func main() {
	app := fiber.New()

	app.Use(logger.New())
	app.Get("/*", func(c *fiber.Ctx) error {
		return c.SendFile("not_found")
	})

	app.Listen("127.0.0.1:3000")
}
```

### PR DESCRIPTION
**Pull request by hi019**
fixes #907

### CODE REVIEW

File: ctx.go [hunk 1]
```diff
@@ -953,7 +953,7 @@ func (c *Ctx) SendFile(file string, compress ...bool) error {
 	}
 	// Check for error
 	if status != StatusNotFound && fsStatus == StatusNotFound {
-		return fmt.Errorf("sendfile: file %s not found", file)
+		return ErrNotFound
```
Comment (kiyonlin) [inline ctx.go:956]: `NewError(StatusNotFound, fmt.Sprintf("sendfile: file %s not found", file))` may be better

**Review by kiyonlin — APPROVED** [review]
